### ISSUE TITLE
Compile failure with base-4.8

### ISSUE THREAD

**Issue by hvr** [tsani/servant-github-webhook#2]
The package declares compatibility with `base >=4.8 && <4.10`, however GHC 7.10 disagrees (`Control.Monad.IO.Class` moved from transformers to base in base-4.9):

```
Configuring component lib from servant-github-webhook-0.3.0.1
Preprocessing library servant-github-webhook-0.3.0.1...

src/Servant/GitHub/Webhook.hs:91:8:
    Could not find module ‘Control.Monad.IO.Class’
    It is a member of the hidden package ‘transformers-0.4.2.0@trans_GZTjP9K5WFq01xC9BAGQpF’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

**Comment by tsani** [comment]
Commit 397a5e4 adds a build flag `old-base` for compilation with base 4.8 by conditionally adding a transformers dependency. I don't have GHC 7.10 installed, so I haven't been able to test the build with the flag set, but this ought to work. The flag should automatically become set by cabal on GHC 7.10 since the `base >=4.9` requirement won't be satisfiable.

Let me know if this works and I'll publish a new version to hackage.

**Comment by hvr** [comment]
@tsani ...if you want, I can help you set you up with Travis-CI so that you can have travis/github continuously check that your package still builds with GHC versions you want to support.

It's mostly a matter of generating a `.travis.yml` file with e.g.

https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs

and go to http://travis-ci.org and enable the CI service for your github repo...

**Comment by tsani** [comment]
@hvr I followed your instructions and got travis working. The library now successfully builds on GHC 7.10.2 and GHC 7.10.3 as well. I can't support GHC 7.10.1 since github-0.15 uses GHC.Stack.CallStack which was introduced in base-4.8.1.

**Comment by hvr** [comment]
@tsani supporting GHC >= 7.10.2 is more than enough :-)
